name: Go

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version:
          - 1.16
        include:
          - go-version: tip
            os: ubuntu-latest
            may-fail: true
    runs-on: ubuntu-latest
    # The environment this job references
    environment:
      name: CI
    steps:
    - name: Set up Go release
      if: matrix.go-version != 'tip'
      uses: percona-platform/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Set up Go tip
      if: matrix.go-version == 'tip'
      env:
        # to avoid error due to `go version` accepting -v flag with an argument since 1.15
        GOFLAGS: ""
      run: |
        git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
        cd $HOME/gotip/src
        ./make.bash
        echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
        echo "$HOME/gotip/bin" >> $GITHUB_PATH
    - name: Checkout code
      uses: percona-platform/checkout@v2
    - name: Build
      run: make build
    - name: "Build and Push event-exporter Image"
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kubestar/rds-exporter
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        platforms: linux/amd64,linux/arm64
        tags: "v0.1,latest"
