name: Go

on: [push, pull_request]

jobs:
  build-and-push-kubestar:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "manifest"
        run: echo `git log | grep commit | head -1 | cut -d" " -f2` > manifest
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-${{ matrix.platform }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ matrix.platform }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.platform }}
      - name: "Build and Push rds-exporter Image"
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kubestar/rds-exporter
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          platforms: linux/arm64
          tags: "v1.0.0"
