name: Go

on: [push, pull_request]

jobs:
  AMD64build:
    name: AMD64build
    runs-on: ubuntu-latest
    steps:
    - name: "checkout go"
      uses: actions/checkout@master
    - name: "setup go"
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Set output
      id: vars
      run: echo "tag=$(date +%Y%m%d%H%M%S)-$(echo ${GITHUB_SHA} | cut -c1-8)-$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g" | sed -e "s/\//-/g")" >> $GITHUB_OUTPUT
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo ${{ steps.vars.outputs.tag }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: "manifest"
      run:  echo `git log | grep commit | head -1 | cut -d" " -f2` > manifest
    - uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.1.0
    - name: Build
      run: make build
    - name: "Build and Push rds-exporter Image"
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: kubestar/rds-exporter
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        platforms: linux/arm64
        tags: "v0.1.0"
